# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '.idea/.*'
      - id: check-yaml

  - repo: https://github.com/jguttman94/pre-commit-gradle
    rev: v0.3.0
    hooks:
      - id: gradle-task
        name: gradle lint
        args: [ "-w", "-o", "lintFix" ]
        types:
          - xml
      - id: gradle-task
        name: gradle detekt
        args: [ "-w", "-o", "detekt --auto-correct" ]
        files: \.kts?$
