name: Autoapproval workflow

on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review, labeled ]
  pull_request_review:
    types: [ dismissed ]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: autoapproval-${{ github.ref }}
  cancel-in-progress: true

jobs:
  autoapproval:
    name: Autoapproval
    runs-on: ubuntu-latest
    if: ${{ contains( github.event.pull_request.labels.*.name, 'ready') && ! github.event.pull_request.draft }}
    steps:

      - name: 'Wait for status checks'
        id: waitforstatuschecks
        uses: "WyriHaximus/github-action-wait-for-status@47d6bc1a0a92ed8a9ba13b060f9f8c40ccd8b3ec"
        with:
          ignoreActions: "Autoapproval"
          checkInterval: 30
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Autoapproval
        uses: pedrox-hs/autoapproval@main
        if: steps.waitforstatuschecks.outputs.status == 'success'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
