name: Autoapproval

on:
  workflow_run:
    workflows:
      - Alls green
    types:
      - completed

jobs:
  autoapproval:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.pull_requests }}
    permissions:
      contents: read
      pull-requests: write
    uses: trilobitech/.github/workflows/autoapproval.yml@main
    with:
      pull_requests: ${{ toJson(github.event.workflow_run.pull_requests) }}
