name: SonarCloud Report

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

concurrency:
  group: sonar-${{ github.event.workflow_run.head_sha || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle/libs.versions.toml', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Download static analysis artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: static-analysis.yml
          path: ./artifacts/
          skip_unpack: true

      - name: Download unit tests artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: unit-test.yml
          path: ./artifacts/
          skip_unpack: true

      - name: Unzip all artifacts
        run: |
          unzip -v 'artifacts/*.zip' -d ./

      - name: Run SonarCloud analysis
        if: ${{ !steps.waitforstatuschecks.outputs.pr }}
        run: |
          ./gradlew sonar --info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
